import type { NormalizedSignal } from "./contracts"

export const redactedSignals = [
  {
    id: "usage:acct_redacted_001:evt_001",
    accountId: "acct_redacted_001",
    accountName: "Northstar Labs",
    ownerName: "A. Rivera",
    source: "usage",
    sourceRecordId: "evt_001",
    observedAt: "2026-09-13T16:30:00.000Z",
    receivedAt: "2026-09-13T16:31:00.000Z",
    title: "Production usage accelerated",
    detail: "Weekly production requests increased 42% over the prior period.",
    direction: "expansion",
    severity: "warning",
    metric: {
      name: "weekly_requests",
      value: 142000,
      unit: "requests",
      previousValue: 100000,
    },
    sourceUrl: null,
  },
  {
    id: "billing:acct_redacted_002:evt_002",
    accountId: "acct_redacted_002",
    accountName: "Harbor Systems",
    ownerName: "M. Chen",
    source: "billing",
    sourceRecordId: "evt_002",
    observedAt: "2026-09-13T19:10:00.000Z",
    receivedAt: "2026-09-13T19:12:00.000Z",
    title: "Payment retry unresolved",
    detail: "A payment retry remains unresolved after the grace period.",
    direction: "risk",
    severity: "critical",
    metric: {
      name: "failed_payment_retries",
      value: 3,
      unit: "retries",
      previousValue: 1,
    },
    sourceUrl: null,
  },
  {
    id: "salesforce:acct_redacted_001:opp_003",
    accountId: "acct_redacted_001",
    accountName: "Northstar Labs",
    ownerName: "A. Rivera",
    source: "salesforce",
    sourceRecordId: "opp_003",
    observedAt: "2026-09-14T08:00:00.000Z",
    receivedAt: "2026-09-14T08:02:00.000Z",
    title: "Expansion opportunity advanced",
    detail: "The account entered a later evaluation stage for additional capacity.",
    direction: "expansion",
    severity: "critical",
    metric: null,
    sourceUrl: null,
  },
] satisfies NormalizedSignal[]
